server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hotel?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.150.101
    port: 5672
    username: root
    password: root001
    virtual-host: /
logging:
  level:
    pers.ervin: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: pers.ervin.hotel.pojo